-- -------------------------------------------------------------
-- 
-- File Name: S:\Documents\ESD2_Final_Project\FPGA_stuff\hdl_prj3\hdlsrc\ImageProcessingNoShift\subtracti_ip_src_Binarize2.vhd
-- Created: 2024-04-27 11:05:49
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: subtracti_ip_src_Binarize2
-- Source Path: ImageProcessingNoShift/subtraction_core/Subsystem1/Binarize2
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY subtracti_ip_src_Binarize2 IS
  PORT( u                                 :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        Out1                              :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END subtracti_ip_src_Binarize2;


ARCHITECTURE rtl OF subtracti_ip_src_Binarize2 IS

  -- Signals
  SIGNAL u_unsigned                       : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Compare_To_Constant_out1         : std_logic;
  SIGNAL Constant_out1                    : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Constant1_out1                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant1_out1_dtc               : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Index_Vector_out1                : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  u_unsigned <= unsigned(u);

  
  Compare_To_Constant_out1 <= '1' WHEN u_unsigned <= to_unsigned(16#23#, 8) ELSE
      '0';

  Constant_out1 <= to_unsigned(16#FF#, 8);

  Constant1_out1 <= to_signed(16#00#, 8);

  Constant1_out1_dtc <= unsigned(Constant1_out1);

  
  Index_Vector_out1 <= Constant_out1 WHEN Compare_To_Constant_out1 = '0' ELSE
      Constant1_out1_dtc;

  Out1 <= std_logic_vector(Index_Vector_out1);

END rtl;

