open_system('gm_ImageProcessingNoShift');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ImageProcessingNoShift/subtraction_core/Subsystem1', 'user2');
annotate_port('gm_ImageProcessingNoShift/subtraction_core/Subsystem1', 1, 1, 'cp : 3.991 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ImageProcessingNoShift/subtraction_core/Subsystem1/Binarize', 'user2');
annotate_port('gm_ImageProcessingNoShift/subtraction_core/Subsystem1/Binarize', 0, 1, 'cp : 2.734 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ImageProcessingNoShift/subtraction_core/Subsystem1/Delay2', 'user1');
annotate_port('gm_ImageProcessingNoShift/subtraction_core/Subsystem1/Delay2', 1, 1, 'cp : 3.991 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ImageProcessingNoShift/subtraction_core/Subsystem1/Bit Concat', 'user2');
annotate_port('gm_ImageProcessingNoShift/subtraction_core/Subsystem1/Bit Concat', 0, 1, 'cp : 3.749 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ImageProcessingNoShift/subtraction_core/Subsystem1/Sum', 'user2');
annotate_port('gm_ImageProcessingNoShift/subtraction_core/Subsystem1/Sum', 0, 1, 'cp : 3.749 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ImageProcessingNoShift/subtraction_core/Subsystem1/gray', 'user1');
annotate_port('gm_ImageProcessingNoShift/subtraction_core/Subsystem1/gray', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ImageProcessingNoShift/subtraction_core/Subsystem1/Binarize/Compare To Constant', 'user2');
annotate_port('gm_ImageProcessingNoShift/subtraction_core/Subsystem1/Binarize/Compare To Constant', 0, 1, 'cp : 1.048 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ImageProcessingNoShift/subtraction_core/Subsystem1/Binarize/Index Vector', 'user2');
annotate_port('gm_ImageProcessingNoShift/subtraction_core/Subsystem1/Binarize/Index Vector', 0, 1, 'cp : 2.734 ns');
