-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\ImageProcessingNoShift\subtracti_ip_src_subtraction_core_pkg.vhd
-- Created: 2024-04-24 10:07:46
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE subtracti_ip_src_subtraction_core_pkg IS
  TYPE vector_of_unsigned64 IS ARRAY (NATURAL RANGE <>) OF unsigned(63 DOWNTO 0);
END subtracti_ip_src_subtraction_core_pkg;

